name: CI

on: [push, pull_request]

jobs:
  deploy:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && contains(github.event.head_commit.message, 'release-android')"

